const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
const SIGN_OUT = 'SIGN_OUT';

//Profile
const PROFILE_FETCHED = 'PROFILE_FETCHED';
const PROFILE_EMPTY = 'PROFILE_EMPTY';
const PROFILE_CREATED_SUCCESSFUL = 'PROFILE_CREATED_SUCCESSFUL';
const PROFILE_CREATED_FAILED = 'PROFILE_CREATED_FAILED';
const CLEAR_PROFILE = 'CLEAR_PROFILE';

export {
  SIGN_IN_SUCCESSFUL,
  SIGN_IN_FAILED,
  SIGN_UP_SUCCESSFUL,
  SIGN_UP_FAILED,
  SIGN_OUT,
  PROFILE_FETCHED,
  PROFILE_CREATED_SUCCESSFUL,
  PROFILE_CREATED_FAILED,
  PROFILE_EMPTY,
  CLEAR_PROFILE,
};
