const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export {SIGN_IN_SUCCESSFUL, SIGN_IN_FAILED, SIGN_UP_SUCCESSFUL, SIGN_UP_FAILED};
